-- ==========================================
-- TECH-STASH SUPABASE SCHEMA CREATION SCRIPT
-- Description: DDL to set up all tables and RLS policies
-- ==========================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables to ensure clean state
DROP TABLE IF EXISTS public.comment_likes CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.snippet_tags CASCADE;
DROP TABLE IF EXISTS public.snippets CASCADE;
DROP TABLE IF EXISTS public.post_tags CASCADE;
DROP TABLE IF EXISTS public.posts CASCADE;
DROP TABLE IF EXISTS public.tags CASCADE;
DROP TABLE IF EXISTS public.languages CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.level_borders CASCADE;
DROP TABLE IF EXISTS public.avatar_frames CASCADE;

-- 1. Table: avatar_frames
CREATE TABLE public.avatar_frames (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    css_class text,
    is_premium boolean DEFAULT false,
    required_level integer DEFAULT 0
);

-- 2. Table: level_borders
CREATE TABLE public.level_borders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    css_class text,
    image_url text,
    min_level integer NOT NULL
);

-- 3. Table: profiles
CREATE TABLE public.profiles (
    id uuid PRIMARY KEY, -- Maps to auth.users.id
    updated_at timestamp with time zone DEFAULT now(),
    full_name text,
    avatar_url text,
    github_url text,
    role text DEFAULT 'user',
    bio text,
    level integer DEFAULT 1,
    coin integer DEFAULT 0,
    current_frame_id uuid REFERENCES public.avatar_frames(id) ON DELETE SET NULL
);

-- 4. Table: languages
CREATE TABLE public.languages (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    slug text NOT NULL UNIQUE
);

-- 5. Table: posts
CREATE TABLE public.posts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    excerpt text,
    content text NOT NULL,
    slug text NOT NULL UNIQUE,
    thumbnail text,
    reading_time integer DEFAULT 1,
    featured boolean DEFAULT false,
    published boolean DEFAULT true,
    language text NOT NULL,
    author_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    language_id uuid REFERENCES public.languages(id) ON DELETE SET NULL
);

-- 6. Table: tags
CREATE TABLE public.tags (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    slug text NOT NULL UNIQUE
);

-- 7. Table: post_tags
CREATE TABLE public.post_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    tag_id uuid NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    UNIQUE(post_id, tag_id)
);

-- 8. Table: snippets
CREATE TABLE public.snippets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    description text,
    code text NOT NULL,
    language text NOT NULL,
    slug text NOT NULL UNIQUE,
    filename text,
    published boolean DEFAULT true,
    author_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    language_id uuid REFERENCES public.languages(id) ON DELETE SET NULL
);

-- 9. Table: snippet_tags
CREATE TABLE public.snippet_tags (
    snippet_id uuid NOT NULL REFERENCES public.snippets(id) ON DELETE CASCADE,
    tag_id uuid NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (snippet_id, tag_id)
);

-- 10. Table: comments
CREATE TABLE public.comments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    post_id uuid NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    content text NOT NULL,
    parent_id uuid REFERENCES public.comments(id) ON DELETE CASCADE
);

-- 11. Table: comment_likes
CREATE TABLE public.comment_likes (
    comment_id uuid NOT NULL REFERENCES public.comments(id) ON DELETE CASCADE,
    profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (comment_id, profile_id)
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.avatar_frames ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.level_borders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.languages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.snippets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.snippet_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- Avatar Frames Policies
CREATE POLICY "Avatar frames are viewable by everyone" ON public.avatar_frames
    FOR SELECT USING (true);

-- Level Borders Policies
CREATE POLICY "Level borders are viewable by everyone" ON public.level_borders
    FOR SELECT USING (true);

-- Languages Policies
CREATE POLICY "Languages are viewable by everyone" ON public.languages
    FOR SELECT USING (true);

-- Posts Policies
CREATE POLICY "Published posts are viewable by everyone" ON public.posts
    FOR SELECT USING (published = true OR auth.uid() = author_id);

CREATE POLICY "Authors can insert posts" ON public.posts
    FOR INSERT WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Authors can update their own posts" ON public.posts
    FOR UPDATE USING (auth.uid() = author_id);

CREATE POLICY "Authors can delete their own posts" ON public.posts
    FOR DELETE USING (auth.uid() = author_id);

-- Tags Policies
CREATE POLICY "Tags are viewable by everyone" ON public.tags
    FOR SELECT USING (true);

-- Post Tags Policies
CREATE POLICY "Post tags are viewable by everyone" ON public.post_tags
    FOR SELECT USING (true);

CREATE POLICY "Post tags are insertable by post authors" ON public.post_tags
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.posts 
            WHERE posts.id = post_tags.post_id AND posts.author_id = auth.uid()
        )
    );

CREATE POLICY "Post tags are deletable by post authors" ON public.post_tags
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.posts 
            WHERE posts.id = post_tags.post_id AND posts.author_id = auth.uid()
        )
    );

-- Snippets Policies
CREATE POLICY "Published snippets are viewable by everyone" ON public.snippets
    FOR SELECT USING (published = true OR auth.uid() = author_id);

CREATE POLICY "Authors can insert snippets" ON public.snippets
    FOR INSERT WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Authors can update their own snippets" ON public.snippets
    FOR UPDATE USING (auth.uid() = author_id);

CREATE POLICY "Authors can delete their own snippets" ON public.snippets
    FOR DELETE USING (auth.uid() = author_id);

-- Snippet Tags Policies
CREATE POLICY "Snippet tags are viewable by everyone" ON public.snippet_tags
    FOR SELECT USING (true);

CREATE POLICY "Snippet tags are insertable by snippet authors" ON public.snippet_tags
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.snippets 
            WHERE snippets.id = snippet_tags.snippet_id AND snippets.author_id = auth.uid()
        )
    );

CREATE POLICY "Snippet tags are deletable by snippet authors" ON public.snippet_tags
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.snippets 
            WHERE snippets.id = snippet_tags.snippet_id AND snippets.author_id = auth.uid()
        )
    );

-- Comments Policies
CREATE POLICY "Comments are viewable by everyone" ON public.comments
    FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert comments" ON public.comments
    FOR INSERT WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Users can update their own comments" ON public.comments
    FOR UPDATE USING (auth.uid() = profile_id);

CREATE POLICY "Users can delete their own comments" ON public.comments
    FOR DELETE USING (auth.uid() = profile_id);

-- Comment Likes Policies
CREATE POLICY "Comment likes are viewable by everyone" ON public.comment_likes
    FOR SELECT USING (true);

CREATE POLICY "Authenticated users can toggle like" ON public.comment_likes
    FOR INSERT WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Users can remove their own likes" ON public.comment_likes
    FOR DELETE USING (auth.uid() = profile_id);
